// utils/youtubeChannelSearch.ts
//
// YouTube Data API v3の薄いラッパー。アーティストの公式チャンネルを特定し、
// そのチャンネルのアップロード済み動画タイトル一覧を取得するためだけに使う
// (1曲ごとのsearch.list呼び出しは1回100ユニットと高コストなため、
// search.listはアーティター単位で1回だけに留める。スクリプト本体
// scripts/backfill-track-youtube-mv.tsの設計コメント参照)。
const API_BASE = 'https://www.googleapis.com/youtube/v3'

export type YoutubeChannelCandidate = {
  channelId: string
  title: string
  description: string
}

export type YoutubeChannelDetail = YoutubeChannelCandidate & {
  subscriberCount: number | null
  uploadsPlaylistId: string | null
}

/** YouTube Data APIの日次クォータ超過(429)を表す専用エラー。呼び出し側
 * (scripts/backfill-track-youtube-mv.ts)がこれを他のエラーと区別できるように
 * するためだけに存在する。クォータ超過は「このアーティストの処理に失敗した」
 * のではなく「そもそも試せていない」状態なので、youtube_mv_backfill_logに
 * 記録して次回スキップ対象にしてはいけない(実際に73件を誤って永久スキップ
 * 扱いにしてしまった不具合があり、その修正として導入した)。 */
export class YoutubeQuotaExceededError extends Error {}

async function throwForResponse(res: Response, callLabel: string): Promise<never> {
  const text = await res.text().catch(() => '')
  if (res.status === 429) {
    throw new YoutubeQuotaExceededError(`YouTube ${callLabel} error: 429 ${text.slice(0, 300)}`)
  }
  throw new Error(`YouTube ${callLabel} error: ${res.status} ${text.slice(0, 300)}`)
}

function getApiKey(): string {
  const apiKey = process.env.YOUTUBE_API_KEY
  if (!apiKey) {
    throw new Error('YOUTUBE_API_KEY が設定されていません。')
  }
  return apiKey
}

// YouTubeが自動生成する「(アーティスト名) - Topic」チャンネルは、本人が管理する
// 公式MV置き場ではなく音源のみの自動チャンネルのため、候補から除外する
function isAutoGeneratedTopicChannel(title: string): boolean {
  return /\s-\sTopic$/.test(title.trim())
}

/** search.list(type=channel)でアーティスト名から候補チャンネルを検索する。
 * 1回呼ぶごとに100ユニット消費する(このモジュールで最も高コストな呼び出し)。 */
export async function searchChannelsByArtistName(artistName: string, maxResults = 5): Promise<YoutubeChannelCandidate[]> {
  const apiKey = getApiKey()
  const url = `${API_BASE}/search?part=snippet&type=channel&maxResults=${maxResults}&q=${encodeURIComponent(artistName)}&key=${apiKey}`
  const res = await fetch(url, { signal: AbortSignal.timeout(20000) })
  if (!res.ok) return throwForResponse(res, 'search.list')
  const data = await res.json()
  const items = (data.items ?? []) as {
    id?: { channelId?: string }
    snippet?: { title?: string; description?: string }
  }[]

  const candidates: YoutubeChannelCandidate[] = []
  for (const item of items) {
    const channelId = item.id?.channelId
    const title = item.snippet?.title
    if (!channelId || !title) continue
    if (isAutoGeneratedTopicChannel(title)) continue
    candidates.push({ channelId, title, description: item.snippet?.description ?? '' })
  }
  return candidates
}

/** channels.listで候補チャンネルの登録者数とアップロード一覧プレイリストIDを
 * まとめて取得する(最大50件まで1回1ユニット)。 */
export async function fetchChannelDetails(channelIds: string[]): Promise<Map<string, YoutubeChannelDetail>> {
  const result = new Map<string, YoutubeChannelDetail>()
  if (channelIds.length === 0) return result

  const apiKey = getApiKey()
  const url = `${API_BASE}/channels?part=snippet,statistics,contentDetails&id=${channelIds.join(',')}&key=${apiKey}`
  const res = await fetch(url, { signal: AbortSignal.timeout(20000) })
  if (!res.ok) return throwForResponse(res, 'channels.list')
  const data = await res.json()
  const items = (data.items ?? []) as {
    id?: string
    snippet?: { title?: string; description?: string }
    statistics?: { subscriberCount?: string; hiddenSubscriberCount?: boolean }
    contentDetails?: { relatedPlaylists?: { uploads?: string } }
  }[]

  for (const item of items) {
    if (!item.id || !item.snippet?.title) continue
    const subscriberCount =
      item.statistics?.hiddenSubscriberCount || !item.statistics?.subscriberCount
        ? null
        : Number(item.statistics.subscriberCount)
    result.set(item.id, {
      channelId: item.id,
      title: item.snippet.title,
      description: item.snippet.description ?? '',
      subscriberCount: Number.isFinite(subscriberCount) ? subscriberCount : null,
      uploadsPlaylistId: item.contentDetails?.relatedPlaylists?.uploads ?? null,
    })
  }
  return result
}

export type YoutubeUploadedVideo = { videoId: string; title: string }

/** チャンネルのアップロード一覧プレイリストから、全動画のID・タイトルを
 * ページング取得する(50件ごとに1ユニット)。 */
export async function fetchUploadedVideos(uploadsPlaylistId: string): Promise<YoutubeUploadedVideo[]> {
  const apiKey = getApiKey()
  const videos: YoutubeUploadedVideo[] = []
  let pageToken: string | undefined

  while (true) {
    const url =
      `${API_BASE}/playlistItems?part=snippet&maxResults=50&playlistId=${uploadsPlaylistId}&key=${apiKey}` +
      (pageToken ? `&pageToken=${pageToken}` : '')
    const res = await fetch(url, { signal: AbortSignal.timeout(20000) })
    if (!res.ok) return throwForResponse(res, 'playlistItems.list')
    const data = await res.json()
    const items = (data.items ?? []) as { snippet?: { title?: string; resourceId?: { videoId?: string } } }[]
    for (const item of items) {
      const videoId = item.snippet?.resourceId?.videoId
      const title = item.snippet?.title
      if (videoId && title) videos.push({ videoId, title })
    }
    pageToken = data.nextPageToken
    if (!pageToken) break
  }

  return videos
}
